module.exports = [
  "AJMER", "ALWAR", "BALOTRA", "BANSWARA", "BARAN", "BARMER", "BEAWAR", "BHARATPUR",
  "BHILWARA", "BIKANER", "BUNDI", "CHITTORGARH", "CHURU", "DAUSA", "DEEG", "DIDWANA-KUCHAMAN",
  "DHOLPUR", "DUNGARPUR", "HANUMANGARH", "JAIPUR", "JAISALMER", "JALORE", "JHALAWAR", "JHUNJHUNU",
  "JODHPUR", "KARAULI", "KHAIRTHAL-TIJARA", "KOTA", "KOTPUTLI-BEHROR", "NAGAUR", "PALI", "PHALODI",
  "PRATAPGARH", "RAJSAMAND", "SALUMBAR", "SAWAI MADHOPUR", "SIKAR", "SIROHI", "SRI GANGANAGAR",
  "TONK", "UDAIPUR"
];